Fix the implementation of socket timeout retry handling.
eclipse-equinox/p2 pull request #233
Opened 2023-03-22 15:13 UTC by merks

Ensure that the map used to save the per-URI retry count is thread safe and ensure that the retry count resets back to zero after a period of time.

2023-03-22 15:18 UTC, merks commented
@laeubi 

I noticed that the implementation maintaining a per-URI retry count via map was not thread safe (nor was the map itself thread safe).   It also seems odd that the retry count can never go back to zero, so I implemented a simple mechanism so that after 10 minutes the retry count will go back to 1.   At least its thread safe now, but still feels kind of ugly, though less horrible than before.  I don't have a better idea for how to fix what was arguably a bit of a hack...

2023-03-23 07:09 UTC, laeubi requested changes
Maybe it should reset the count once a successful attempt was made as well?

2023-03-23 07:09 UTC, laeubi commented on bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/RepositoryTransport.java
> +		long LIFETIME = 10 * 60 * 1000;
```suggestion
		long LIFETIME = TimeUnit.MINUTES.toMillis(10);
```

2023-03-23 07:09 UTC, laeubi commented on bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/RepositoryTransport.java
> +		int increment() {
```suggestion
		synchronized int increment() {
```
Otherwise this is not concurrency safe!

2023-03-23 09:10 UTC, laeubi commented
The last modified and download methods seems like a good place to reset if they succeed without the need to do it everywhere.

2023-03-24 10:44 UTC, merks commented
This still seems to be blocked.  I'd like to merge as is because while not perfect it's better than what's there now, which is definitely not thread safe and will definitely timeout forever after the first time.  If you want to further improve it, you can do so.  But I have limited time for that purpose.

2023-03-24 11:00 UTC, laeubi approved these changes
Concurrency issues seems to be addressed now.

2023-03-24 11:04 UTC, merged

2023-03-24 11:05 UTC, merks commented
BTW, I think are correct that one could do stuff in download and last modified if one guarded all the return points.   The stream method isn't so clear.  But you and I probably both have bigger fish to fry.  😄