MT hardening FileInfoReader #568
eclipse-equinox/p2 pull request #569
Opened 2024-11-18 14:56 UTC by jukzi

The value of the barrier (true/false) was never read. It was only checked for !=null. The value had been read in waitOnSelf() without any multithreading semantics like synchronize/volatile. Instead now we use a thread safe AtomicBoolean. The synchronization blocks are still used for wait()/notifyAll()

https://github.com/eclipse-equinox/p2/issues/568

2024-11-18 15:00 UTC, laeubi requested changes
The purpose of the group of `Atomic` primitives is that they don't require any synchronization at all (and some tools will complain that this is code-smell).

Why not use a real barrier (e.g. `CountDownLatch`) here that do not require syncronization.

2024-11-18 15:03 UTC, laeubi commented on bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileInfoReader.java
> +		while (!barrierReached.get()) {
I must confess that I can't get what is the purpose of this loop... if I schedule a job **once** how can I **join** it more than once?

@merks any clue whats the purpose of this?

2024-11-18 15:04 UTC, jukzi commented
CountDownLatch can not be reset. CyclicBarrier can be reset but not read/mixed with the wait loop that askes for cancel. If you find any better solution please do. Meanwhile this could improve the situation.

2024-11-18 15:06 UTC, laeubi commented on bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileInfoReader.java
> +			while (!barrierReached.get()) {
This changes behavior before any value TRUE/FALSE would have ended the loop now it loops forever if set to false.

2024-11-18 15:26 UTC, merks commented
We're in the RC2 phase so **nothing** will get done for this release. 

I'm really uncomfortable changing something here simply because we theorize that it might be broken with no reproducible way to test that we've actually fixed what we think is the problem rather than simply changed the behavior a bit and hoping for the best that this somehow helps something. How many times has even the most simple, innocent change broken something?  I've lost count.   But that's just my opinion and perhaps it's simply paranoia...

2024-11-18 15:41 UTC, jukzi commented
I don't want this for any RC but M1. Simply adding a synchronize around an endless loop would harm more then help: The only use of synchronize in that class is the notify/wait mechanism  - that does not exist in waitOnSelf().

2024-11-18 16:08 UTC, laeubi commented
> Simply adding a synchronize around an endless loop would harm more then help:

I didn't suggested to put it _around_ the loop ...

> The only use of synchronize in that class is the notify/wait mechanism - that does not exist in waitOnSelf().

Then please fix up the PR/Commit message this PR seem to do something different then.

2024-12-12 08:55 UTC, jukzi commented
> Maybe it would be better to have two PRs for two things as well.

@laeubi please provide such.

2024-12-12 08:55 UTC, closed without merging